#!/bin/bash
(cd dalangi && git add --update && git commit -m "tmp" && git push)
(cd dartflow && git add --update && git commit -m "tmp" && git push)
(cd dart_analyses_common && git add --update && git commit -m "tmp" && git push)
(cd goodenough && git add --update && git commit -m "tmp" && git push)