#!/bin/bash
(cd dalangi && git add --update && git commit -m "tmp" && git push)
(cd dataflow && git add --update && git commit -m "tmp" && git push)
(cd common && git add --update && git commit -m "tmp" && git push)
(cd goodenough && git add --update && git commit -m "tmp" && git push)