name: goodenough
description: Hybrid Type Analysis for Dart
dependencies:
  ansicolor: ">=0.0.9 <0.1.0"
  barback: '>=0.15.0 <0.16.0'
  dart_style: "any"
  vacuum_persistent: "^2.0.0"
  avl_tree: "0.1.1+1"
  dartlings: "^0.2.0"
  quiver: "^0.21.4"
  json_schema: "1.0.1"
  quiver: any
  args: ">=0.12.1 <0.14.0"
  path: "^1.3.6"
  dartson: "^0.2.5"
  code_transformers: any
  data_flow_analysis:
    path: all-deps/dartflow
  common:
    path: all-deps/dart_analyses_common
  dart_sdk_dependencies:
    git:
      url: https://github.com/algobardo/dart_sdk_dependencies.git
      ref: v1.12.2
  dalangi:
    path: all-deps/dalangi
  analyzer: ">=0.26.1-alpha.0 <0.27.0"

dev_dependencies:
  scheduled_test: '^0.12.2'
environment:
  sdk: ">1.11.0"
executables:
  goodenough:
