#!/bin/bash
git clone git@casadev.cs.au.dk:DART/goodenough.git
git clone git@casadev.cs.au.dk:DART/dart_analyses_common.git
git clone git@casadev.cs.au.dk:DART/dalangi.git
git clone git@casadev.cs.au.dk:DART/dartflow.git
