#!/bin/bash
git clone https://github.com/cs-au-dk/goodenough.git
cd goodenough
mkdir deps
cd deps 
git clone https://github.com/cs-au-dk/dart_analyses_common.git
git clone https://github.com/cs-au-dk/dalangi.git
git clone https://github.com/cs-au-dk/dartflow.git
