name: root
dependencies:
  dalangi:
    path: dalangi
  data_flow_analysis:
    path: dataflow
  goodenough: 
    path: goodenough
  common: 
    path: common

dependency_overrides:
  common:
    path: common
  dalangi:
    path: dalangi
  data_flow_analysis:
    path: dataflow
  goodenough:
    path: goodenough
